site_url: https://opendatasicilia.github.io/emergenza-idrica-sicilia/
site_name: Emergenza idrica in Sicilia
site_author: by OpenDataSicilia.it
theme:
  name: material
  language: it
  icon:
    logo: material/water
    annotation: material/star-four-points-circle

  favicon: img/favicon.ico

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.share
    - navigation.footer
    - toc.follow
    - content.action.edit
    - content.action.view

repo_url: https://github.com/opendatasicilia/emergenza-idrica-sicilia
edit_uri: edit/main/docs/

## Page tree
nav:
  - Home: index.md
  - Mappe: 
     - Comuni con riduzione della fornitura idrica: mappe/riduzione/index.md
     - Principali risorse idriche: mappe/risorse/index.md
     - Dighe e prostetto dei volumi invasati: mappe/volumi/index.md
  - Buone pratiche: buone-pratiche/index.md
  - Documenti utili: documenti-utili/index.md


plugins:
- search
- social

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - tables
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - toc:
      permalink: true


extra_javascript:
  - javascripts/varie.js
