site_url: https://opendatasicilia.github.io/emergenza-idrica-sicilia/
site_name: Emergenza idrica in Sicilia
site_author: by OpenDataSicilia.it
theme:
  name: material
  language: it
  icon:
    logo: material/water
    annotation: material/star-four-points-circle

  favicon: img/favicon.ico

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.share
    - navigation.footer
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.code.copy
    

repo_url: https://github.com/opendatasicilia/emergenza-idrica-sicilia
edit_uri: edit/main/docs/

## Page tree
nav:
  - Home: index.md
  - Mappe: 
     - Comuni con riduzione della fornitura idrica: mappe/riduzione/index.md
     - Principali risorse idriche: mappe/risorse/index.md
     - Dighe e prostetto dei volumi invasati: mappe/volumi/index.md
  - Buone pratiche: buone-pratiche/index.md
  - Documenti utili: documenti-utili/index.md
  - Interventi prioritari: documenti-utili/interventi-2-relazione-cabinaregia-nazionale.md
  - Chi siamo: ods/index.md


plugins:
- search
- social

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - tables
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - toc:
      permalink: true


extra_javascript:
  - javascripts/varie.js
  
  
## Social Media
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/opendatasicilia
      name: account X
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/opendatasicilia/
      name: gruppo facebook
    - icon: fontawesome/brands/telegram
      link: https://t.me/opendatasicilia
      name: gruppo Telegram
    - icon: fontawesome/solid/envelope
      link: https://groups.google.com/forum/#!forum/opendatasicilia
      name: mailing list OpenDataSicilia
    - icon: fontawesome/brands/creative-commons
      link: https://creativecommons.org/licenses/by-sa/4.0/deed.it
      name: Attribuzione - Condividi allo stesso modo 4.0 Internazionale (CC BY-SA 4.0)       
